name: Test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
jobs:
  opa-tests:
    name: OPA tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod 755 ./opa
          sudo mv ./opa /usr/local/bin
      - name: OPA Format
        run: |
          opa fmt --fail . 2> /dev/null
          if [ -n "$?" ]; then
            echo "=== The following files are not formatted ==="
            opa fmt --list .
            exit 1
          fi
      - name: OPA Test
        run: opa test kubernetes/ docker/
